# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f10c184054e610a74771775fab1e1188b6ced0948c23cc19226526c9ad9766e5f91880688f3fed505aca7181bd266915ca3abd5a9d7d254e980b8870c2aa34d8

test:
  secret_key_base: 1f538246adb04bd98fee022e47561061855a6534ac222a0fb16ef820fb5a5ec4f2fe02dc2f40d9f5e0ea0809bfff2fa6178b586b76e0232cc72632f60807f37f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
